#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi
# Redirect output to stderr.
exec 1>&2

git diff --cached --diff-filter=A -z $against | grep -E 'dir\s?='

if test $? = 0
then
	echo "Cannot use 'dir =', must use github repos"
	exit 1
fi
