local select_module = require('nvim-treesitter-textobjects.select')
local move_module = require("nvim-treesitter-textobjects.move")
local mappings_utils = require('config/mappings/utils')

local set = mappings_utils.set

set("sl", function()
  require("nvim-treesitter-textobjects.swap").swap_next("@parameter.inner")
end)

set("sh", function()
  require("nvim-treesitter-textobjects.swap").swap_previous("@parameter.inner")
end)

vim.keymap.set({ "x", "o" }, "af", function()
  select_module.select_textobject("@function.outer", "textobjects")
end)
vim.keymap.set({ "x", "o" }, "if", function()
  select_module.select_textobject("@function.inner", "textobjects")
end)
vim.keymap.set({ "x", "o" }, "aa", function()
  select_module.select_textobject("@parameter.outer", "textobjects")
end)
vim.keymap.set({ "x", "o" }, "ia", function()
  select_module.select_textobject("@parameter.inner", "textobjects")
end)
vim.keymap.set({ "x", "o" }, "ab", function()
  select_module.select_textobject("@local.scope", "locals")
end)

vim.keymap.set({ "n", "x", "o" }, "]f", function()
  move_module.goto_next_start("@function.outer", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "[f", function()
  move_module.goto_previous_start("@function.outer", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "]a", function()
  move_module.goto_next_start("@parameter.outer", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "[a", function()
  move_module.goto_previous_start("@parameter.outer", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "]b", function()
  move_module.goto_next_start("@local.scope", "locals")
end)
vim.keymap.set({ "n", "x", "o" }, "[b", function()
  move_module.goto_previous_start("@local.scope", "locals")
end)
vim.keymap.set({ "n", "x", "o" }, "]z", function()
  move_module.goto_next_start("@fold", "folds")
end)
vim.keymap.set({ "n", "x", "o" }, "[z", function()
  move_module.goto_previous_start("@fold", "folds")
end)
vim.keymap.set({ "n", "x", "o" }, "]gc", function()
  move_module.goto_next_start("@comment.outer", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "[gc", function()
  move_module.goto_previous_start("@comment.outer", "textobjects")
end)

