local select_module = require('nvim-treesitter-textobjects.select')
local move_module = require("nvim-treesitter-textobjects.move")
local set = require('config/api').keymap.leader

set("sl", function()
  require("nvim-treesitter-textobjects.swap").swap_next("@parameter.inner")
end, "Swap parameter with next")

set("sh", function()
  require("nvim-treesitter-textobjects.swap").swap_previous("@parameter.inner")
end, "Swap parameter with previous")

vim.keymap.set({ "x", "o" }, "af", function()
  select_module.select_textobject("@function.outer", "textobjects")
end, { desc = "Select around function" })
vim.keymap.set({ "x", "o" }, "if", function()
  select_module.select_textobject("@function.inner", "textobjects")
end, { desc = "Select inside function" })
vim.keymap.set({ "x", "o" }, "aa", function()
  select_module.select_textobject("@parameter.outer", "textobjects")
end, { desc = "Select around parameter" })
vim.keymap.set({ "x", "o" }, "ia", function()
  select_module.select_textobject("@parameter.inner", "textobjects")
end, { desc = "Select inside parameter" })
vim.keymap.set({ "x", "o" }, "ab", function()
  select_module.select_textobject("@local.scope", "locals")
end, { desc = "Select local scope" })

vim.keymap.set({ "n", "x", "o" }, "]f", function()
  move_module.goto_next_start("@function.outer", "textobjects")
end, { desc = "Go to next function start" })
vim.keymap.set({ "n", "x", "o" }, "[f", function()
  move_module.goto_previous_start("@function.outer", "textobjects")
end, { desc = "Go to previous function start" })
vim.keymap.set({ "n", "x", "o" }, "]a", function()
  move_module.goto_next_start("@parameter.outer", "textobjects")
end, { desc = "Go to next parameter" })
vim.keymap.set({ "n", "x", "o" }, "[a", function()
  move_module.goto_previous_start("@parameter.outer", "textobjects")
end, { desc = "Go to previous parameter" })
vim.keymap.set({ "n", "x", "o" }, "]b", function()
  move_module.goto_next_start("@local.scope", "locals")
end, { desc = "Go to next local scope" })
vim.keymap.set({ "n", "x", "o" }, "[b", function()
  move_module.goto_previous_start("@local.scope", "locals")
end, { desc = "Go to previous local scope" })
vim.keymap.set({ "n", "x", "o" }, "]z", function()
  move_module.goto_next_start("@fold", "folds")
end, { desc = "Go to next fold" })
vim.keymap.set({ "n", "x", "o" }, "[z", function()
  move_module.goto_previous_start("@fold", "folds")
end, { desc = "Go to previous fold" })
vim.keymap.set({ "n", "x", "o" }, "]gc", function()
  move_module.goto_next_start("@comment.outer", "textobjects")
end, { desc = "Go to next comment" })
vim.keymap.set({ "n", "x", "o" }, "[gc", function()
  move_module.goto_previous_start("@comment.outer", "textobjects")
end, { desc = "Go to previous comment" })

